package com.distributedexam.dao;
import com.distributedexam.common.Incident; import java.sql.*; import java.util.*;
public class IncidentDAOImpl implements IncidentDAO {
 public void create(Incident x)throws Exception{String q="INSERT INTO incidents(exam_id,room_id,student_id,type,severity,description,status,resolved_at) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){nullable(s,1,x.getExamId());nullable(s,2,x.getRoomId());nullable(s,3,x.getStudentId());s.setString(4,x.getType());s.setString(5,x.getSeverity());s.setString(6,x.getDescription());s.setString(7,x.getStatus()==null?"OPEN":x.getStatus());s.setTimestamp(8,x.getResolvedAt());s.executeUpdate();try(ResultSet k=s.getGeneratedKeys()){if(k.next())x.setIncidentId(k.getInt(1));}}}
 public void update(Incident x)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("UPDATE incidents SET type=?,severity=?,description=?,status=?,resolved_at=? WHERE incident_id=?")){s.setString(1,x.getType());s.setString(2,x.getSeverity());s.setString(3,x.getDescription());s.setString(4,x.getStatus());s.setTimestamp(5,x.getResolvedAt());s.setInt(6,x.getIncidentId());if(s.executeUpdate()!=1)throw new SQLException("Incident not found: "+x.getIncidentId());}}
 public Incident findById(int id)throws Exception{return one("SELECT * FROM incidents WHERE incident_id=?",id);}
 public List<Incident> findOpen()throws Exception{return many("SELECT * FROM incidents WHERE status <> 'RESOLVED' ORDER BY created_at DESC",null);}
 public List<Incident> findByRoom(int id)throws Exception{return many("SELECT * FROM incidents WHERE room_id=? ORDER BY created_at DESC",id);}
 private Incident one(String q,int id)throws Exception{List<Incident> r=many(q,id);return r.isEmpty()?null:r.get(0);} private List<Incident> many(String q,Integer id)throws Exception{List<Incident> out=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement(q)){if(id!=null)s.setInt(1,id);try(ResultSet r=s.executeQuery()){while(r.next())out.add(map(r));}}return out;}
 private Incident map(ResultSet r)throws SQLException{Incident x=new Incident();x.setIncidentId(r.getInt("incident_id"));x.setExamId(num(r,"exam_id"));x.setRoomId(num(r,"room_id"));x.setStudentId(num(r,"student_id"));x.setType(r.getString("type"));x.setSeverity(r.getString("severity"));x.setDescription(r.getString("description"));x.setStatus(r.getString("status"));x.setCreatedAt(r.getTimestamp("created_at"));x.setResolvedAt(r.getTimestamp("resolved_at"));return x;} private static Integer num(ResultSet r,String n)throws SQLException{int x=r.getInt(n);return r.wasNull()?null:x;} private static void nullable(PreparedStatement s,int i,Integer x)throws SQLException{if(x==null)s.setNull(i,Types.INTEGER);else s.setInt(i,x);}
}
